name: Deploy To VM on GCP

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          echo "=== 디스크 정리 전 상태 ==="
          df -h
          
          # 불필요한 대용량 패키지 제거 (약 12-14GB 확보)
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          
          # 추가 정리
          sudo apt-get remove -y '^aspnetcore-.*' || true
          sudo apt-get remove -y '^dotnet-.*' --fix-missing || true
          sudo apt-get remove -y '^llvm-.*' --fix-missing || true
          sudo apt-get remove -y 'php.*' --fix-missing || true
          sudo apt-get autoremove -y
          
          # Docker 캐시 정리
          docker system prune -af --volumes
          
          # APT 캐시 정리
          sudo apt-get clean
          
          echo "=== 디스크 정리 후 상태 ==="
          df -h

      - name: Get Git short SHA
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create config.py
        run: |
          echo "${{ secrets.CONFIG_PY }}" > app/domain/config.py
          ls -la yolov8s.pt
          echo "config.py created from GitHub Secret"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gangajikimi-ai:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/gangajikimi-ai:${{ steps.vars.outputs.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/gangajikimi-ai:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/gangajikimi-ai:buildcache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            # 디스크 공간 정리 (용량 최적화)
            docker system df
            
            # 사용하지 않는 이미지만 안전하게 정리
            docker image prune -af
            docker container prune -f
            
            docker system df
            
            # 기존 컨테이너 중지 및 제거 (있을 경우)
            docker stop gangajikimi-api || true
            docker rm gangajikimi-api || true
            
            # 최신 이미지 pull
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/gangajikimi-ai:latest
            
            # 새 컨테이너 실행
            docker run -d \
              --name gangajikimi-api \
              --restart unless-stopped \
              -p 8000:8000 \
              ${{ secrets.DOCKERHUB_USERNAME }}/gangajikimi-ai:latest
            
            echo "=== 배포 완료 ==="
            docker ps | grep gangajikimi-api
          EOF
